version: '3.9'

services:
  database:
    container_name: bot-service-db
    image: postgres
    environment:
      POSTGRES_USER: bot-service
      POSTGRES_PASSWORD: bot-service
      POSTGRES_DB: bot-service
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5